module.exports = {
	//入口文件
	entry:'./main.js',
	//输出文件及位置
	output:{
		path:__dirname+'/publicGood',
		filename:'mained.js'
	},
	resolve:{
		alias:{
			vue:'vue/dist/vue.js'
		}
	},
	module:{
		loaders:[{
			test:/\.js$/,
			loader:'babel-loader'
		},{
			test:/\.css$/,
			loader:'style-loader!css-loader'
		},{
			test:/\.scss$/,
			loader:'style-loader!css-loader!sass-loader'
		},{
			test:/\.vue$/,
			loader:'vue-loader'
		},{
			test:/\.ttf$/,
			loader:'file-loader'
		},{
			test:/\.(png|jpg|gif|jpeg)$/,
			loader:'url-loader'
		},]
	},
	devServer:{
		contentBase:'./publicGood',
		port:'52061',
		inline:true
	}
}